//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KassaExpert.FonConnector.Lib.RegKassaService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://finanzonline.bmf.gv.at/rkdb", ConfigurationName="KassaExpert.FonConnector.Lib.RegKassaService.rkdbServicePort")]
    internal interface rkdbServicePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="rkdb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KassaExpert.FonConnector.Lib.RegKassaService.rkdbResponse1> rkdbAsync(KassaExpert.FonConnector.Lib.RegKassaService.rkdbRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class rkdbRequest
    {
        
        private string tidField;
        
        private string benidField;
        
        private string idField;
        
        private art_uebermittlung art_uebermittlungField;
        
        private bool erzwinge_asynchronField;
        
        private bool erzwinge_asynchronFieldSpecified;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tid
        {
            get
            {
                return this.tidField;
            }
            set
            {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string benid
        {
            get
            {
                return this.benidField;
            }
            set
            {
                this.benidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public art_uebermittlung art_uebermittlung
        {
            get
            {
                return this.art_uebermittlungField;
            }
            set
            {
                this.art_uebermittlungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool erzwinge_asynchron
        {
            get
            {
                return this.erzwinge_asynchronField;
            }
            set
            {
                this.erzwinge_asynchronField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool erzwinge_asynchronSpecified
        {
            get
            {
                return this.erzwinge_asynchronFieldSpecified;
            }
            set
            {
                this.erzwinge_asynchronFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rkdb", typeof(rkdb), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("status_ggs", typeof(status_ggs), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("status_kasse", typeof(status_kasse), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("status_see", typeof(status_see), Order=5)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public enum art_uebermittlung
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        P,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class rkdb
    {
        
        private string fastnrField;
        
        private string paket_nrField;
        
        private System.DateTime ts_erstellungField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fastnr
        {
            get
            {
                return this.fastnrField;
            }
            set
            {
                this.fastnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string paket_nr
        {
            get
            {
                return this.paket_nrField;
            }
            set
            {
                this.paket_nrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ts_erstellung
        {
            get
            {
                return this.ts_erstellungField;
            }
            set
            {
                this.ts_erstellungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ausfall_ggs", typeof(ausfall_ggs), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("ausfall_kasse", typeof(ausfall_kasse), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("ausfall_se", typeof(ausfall_se), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("belegpruefung", typeof(belegpruefung), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("registrierung_ggs", typeof(registrierung_ggs), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("registrierung_kasse", typeof(registrierung_kasse), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("registrierung_se", typeof(registrierung_se), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("wiederinbetriebnahme_ggs", typeof(wiederinbetriebnahme_ggs), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("wiederinbetriebnahme_kasse", typeof(wiederinbetriebnahme_kasse), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("wiederinbetriebnahme_se", typeof(wiederinbetriebnahme_se), Order=3)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class ausfall_ggs
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private art_ob art_obField;
        
        private string obField;
        
        private string zusatz_obField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public art_ob art_ob
        {
            get
            {
                return this.art_obField;
            }
            set
            {
                this.art_obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ob
        {
            get
            {
                return this.obField;
            }
            set
            {
                this.obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string zusatz_ob
        {
            get
            {
                return this.zusatz_obField;
            }
            set
            {
                this.zusatz_obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ausfall", typeof(ausfall), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("ausserbetriebnahme", typeof(ausserbetriebnahme), Order=5)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public enum art_ob
    {
        
        /// <remarks/>
        UID,
        
        /// <remarks/>
        GLN,
        
        /// <remarks/>
        FASTNR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class ausfall
    {
        
        private int begruendungField;
        
        private System.DateTime beginn_ausfallField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int begruendung
        {
            get
            {
                return this.begruendungField;
            }
            set
            {
                this.begruendungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime beginn_ausfall
        {
            get
            {
                return this.beginn_ausfallField;
            }
            set
            {
                this.beginn_ausfallField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class ausserbetriebnahme
    {
        
        private int begruendungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int begruendung
        {
            get
            {
                return this.begruendungField;
            }
            set
            {
                this.begruendungField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class ausfall_kasse
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private string kassenidentifikationsnummerField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string kassenidentifikationsnummer
        {
            get
            {
                return this.kassenidentifikationsnummerField;
            }
            set
            {
                this.kassenidentifikationsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ausfall", typeof(ausfall), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("ausserbetriebnahme", typeof(ausserbetriebnahme), Order=3)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class ausfall_se
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private zertifikatsseriennummer zertifikatsseriennummerField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public zertifikatsseriennummer zertifikatsseriennummer
        {
            get
            {
                return this.zertifikatsseriennummerField;
            }
            set
            {
                this.zertifikatsseriennummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ausfall", typeof(ausfall), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("ausserbetriebnahme", typeof(ausserbetriebnahme), Order=3)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class zertifikatsseriennummer
    {
        
        private bool hexField;
        
        private bool hexFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool hex
        {
            get
            {
                return this.hexField;
            }
            set
            {
                this.hexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hexSpecified
        {
            get
            {
                return this.hexFieldSpecified;
            }
            set
            {
                this.hexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class belegpruefung
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private string belegField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string beleg
        {
            get
            {
                return this.belegField;
            }
            set
            {
                this.belegField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class registrierung_ggs
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private art_ob art_obField;
        
        private string obField;
        
        private string zusatz_obField;
        
        private art_se_ggs art_se_ggsField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public art_ob art_ob
        {
            get
            {
                return this.art_obField;
            }
            set
            {
                this.art_obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ob
        {
            get
            {
                return this.obField;
            }
            set
            {
                this.obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string zusatz_ob
        {
            get
            {
                return this.zusatz_obField;
            }
            set
            {
                this.zusatz_obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public art_se_ggs art_se_ggs
        {
            get
            {
                return this.art_se_ggsField;
            }
            set
            {
                this.art_se_ggsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("public_key", typeof(string), Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("zertifikat", typeof(string), Order=6)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public enum art_se_ggs
    {
        
        /// <remarks/>
        EIGENES_HSM,
        
        /// <remarks/>
        SW_GGS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://finanzonline.bmf.gv.at/rkdb", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        public_key,
        
        /// <remarks/>
        zertifikat,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class registrierung_kasse
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private string kassenidentifikationsnummerField;
        
        private string anmerkungField;
        
        private string benutzerschluesselField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string kassenidentifikationsnummer
        {
            get
            {
                return this.kassenidentifikationsnummerField;
            }
            set
            {
                this.kassenidentifikationsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string anmerkung
        {
            get
            {
                return this.anmerkungField;
            }
            set
            {
                this.anmerkungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string benutzerschluessel
        {
            get
            {
                return this.benutzerschluesselField;
            }
            set
            {
                this.benutzerschluesselField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class registrierung_se
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private art_se art_seField;
        
        private string vda_idField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public art_se art_se
        {
            get
            {
                return this.art_seField;
            }
            set
            {
                this.art_seField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string vda_id
        {
            get
            {
                return this.vda_idField;
            }
            set
            {
                this.vda_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zertifikat", typeof(string), Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("zertifikatsseriennummer", typeof(zertifikatsseriennummer), Order=4)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public enum art_se
    {
        
        /// <remarks/>
        SIGNATURKARTE,
        
        /// <remarks/>
        EIGENES_HSM,
        
        /// <remarks/>
        HSM_DIENSTLEISTER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class wiederinbetriebnahme_ggs
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private art_ob art_obField;
        
        private string obField;
        
        private string zusatz_obField;
        
        private System.DateTime ende_ausfallField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public art_ob art_ob
        {
            get
            {
                return this.art_obField;
            }
            set
            {
                this.art_obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ob
        {
            get
            {
                return this.obField;
            }
            set
            {
                this.obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string zusatz_ob
        {
            get
            {
                return this.zusatz_obField;
            }
            set
            {
                this.zusatz_obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ende_ausfall
        {
            get
            {
                return this.ende_ausfallField;
            }
            set
            {
                this.ende_ausfallField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class wiederinbetriebnahme_kasse
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private string kassenidentifikationsnummerField;
        
        private System.DateTime ende_ausfallField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string kassenidentifikationsnummer
        {
            get
            {
                return this.kassenidentifikationsnummerField;
            }
            set
            {
                this.kassenidentifikationsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ende_ausfall
        {
            get
            {
                return this.ende_ausfallField;
            }
            set
            {
                this.ende_ausfallField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class wiederinbetriebnahme_se
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private zertifikatsseriennummer zertifikatsseriennummerField;
        
        private System.DateTime ende_ausfallField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public zertifikatsseriennummer zertifikatsseriennummer
        {
            get
            {
                return this.zertifikatsseriennummerField;
            }
            set
            {
                this.zertifikatsseriennummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ende_ausfall
        {
            get
            {
                return this.ende_ausfallField;
            }
            set
            {
                this.ende_ausfallField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class status_ggs
    {
        
        private string fastnrField;
        
        private string paket_nrField;
        
        private System.DateTime ts_erstellungField;
        
        private string satznrField;
        
        private art_ob art_obField;
        
        private string obField;
        
        private string zusatz_obField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fastnr
        {
            get
            {
                return this.fastnrField;
            }
            set
            {
                this.fastnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string paket_nr
        {
            get
            {
                return this.paket_nrField;
            }
            set
            {
                this.paket_nrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ts_erstellung
        {
            get
            {
                return this.ts_erstellungField;
            }
            set
            {
                this.ts_erstellungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public art_ob art_ob
        {
            get
            {
                return this.art_obField;
            }
            set
            {
                this.art_obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ob
        {
            get
            {
                return this.obField;
            }
            set
            {
                this.obField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string zusatz_ob
        {
            get
            {
                return this.zusatz_obField;
            }
            set
            {
                this.zusatz_obField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class status_kasse
    {
        
        private string fastnrField;
        
        private string paket_nrField;
        
        private System.DateTime ts_erstellungField;
        
        private string satznrField;
        
        private string kassenidentifikationsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fastnr
        {
            get
            {
                return this.fastnrField;
            }
            set
            {
                this.fastnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string paket_nr
        {
            get
            {
                return this.paket_nrField;
            }
            set
            {
                this.paket_nrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ts_erstellung
        {
            get
            {
                return this.ts_erstellungField;
            }
            set
            {
                this.ts_erstellungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string kassenidentifikationsnummer
        {
            get
            {
                return this.kassenidentifikationsnummerField;
            }
            set
            {
                this.kassenidentifikationsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class status_see
    {
        
        private string fastnrField;
        
        private string paket_nrField;
        
        private System.DateTime ts_erstellungField;
        
        private string satznrField;
        
        private zertifikatsseriennummer zertifikatsseriennummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fastnr
        {
            get
            {
                return this.fastnrField;
            }
            set
            {
                this.fastnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string paket_nr
        {
            get
            {
                return this.paket_nrField;
            }
            set
            {
                this.paket_nrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ts_erstellung
        {
            get
            {
                return this.ts_erstellungField;
            }
            set
            {
                this.ts_erstellungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public zertifikatsseriennummer zertifikatsseriennummer
        {
            get
            {
                return this.zertifikatsseriennummerField;
            }
            set
            {
                this.zertifikatsseriennummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class rkdbResponse
    {
        
        private string fastnrField;
        
        private string paket_nrField;
        
        private art_uebermittlung art_uebermittlungField;
        
        private bool art_uebermittlungFieldSpecified;
        
        private System.DateTime ts_erstellungField;
        
        private string infoField;
        
        private result[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fastnr
        {
            get
            {
                return this.fastnrField;
            }
            set
            {
                this.fastnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string paket_nr
        {
            get
            {
                return this.paket_nrField;
            }
            set
            {
                this.paket_nrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public art_uebermittlung art_uebermittlung
        {
            get
            {
                return this.art_uebermittlungField;
            }
            set
            {
                this.art_uebermittlungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool art_uebermittlungSpecified
        {
            get
            {
                return this.art_uebermittlungFieldSpecified;
            }
            set
            {
                this.art_uebermittlungFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ts_erstellung
        {
            get
            {
                return this.ts_erstellungField;
            }
            set
            {
                this.ts_erstellungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("result", Order=5)]
        public result[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class result
    {
        
        private string satznrField;
        
        private string kundeninfoField;
        
        private rkdbMessage[] rkdbMessageField;
        
        private verificationResult[] verificationResultListField;
        
        private abfrage_ergebnis abfrage_ergebnisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string satznr
        {
            get
            {
                return this.satznrField;
            }
            set
            {
                this.satznrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kundeninfo
        {
            get
            {
                return this.kundeninfoField;
            }
            set
            {
                this.kundeninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rkdbMessage", Order=2)]
        public rkdbMessage[] rkdbMessage
        {
            get
            {
                return this.rkdbMessageField;
            }
            set
            {
                this.rkdbMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("verificationResult", IsNullable=false)]
        public verificationResult[] verificationResultList
        {
            get
            {
                return this.verificationResultListField;
            }
            set
            {
                this.verificationResultListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public abfrage_ergebnis abfrage_ergebnis
        {
            get
            {
                return this.abfrage_ergebnisField;
            }
            set
            {
                this.abfrage_ergebnisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class rkdbMessage
    {
        
        private string rcField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class verificationResult
    {
        
        private string verificationIdField;
        
        private string versionField;
        
        private string verificationNameField;
        
        private string verificationTextualDescriptionField;
        
        private verificationState verificationStateField;
        
        private string verificationResultDetailedMessageField;
        
        private input inputField;
        
        private output outputField;
        
        private System.DateTime verificationTimestampField;
        
        private verificationResult[] verificationResultListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string verificationId
        {
            get
            {
                return this.verificationIdField;
            }
            set
            {
                this.verificationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string verificationName
        {
            get
            {
                return this.verificationNameField;
            }
            set
            {
                this.verificationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string verificationTextualDescription
        {
            get
            {
                return this.verificationTextualDescriptionField;
            }
            set
            {
                this.verificationTextualDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public verificationState verificationState
        {
            get
            {
                return this.verificationStateField;
            }
            set
            {
                this.verificationStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string verificationResultDetailedMessage
        {
            get
            {
                return this.verificationResultDetailedMessageField;
            }
            set
            {
                this.verificationResultDetailedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public input input
        {
            get
            {
                return this.inputField;
            }
            set
            {
                this.inputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public output output
        {
            get
            {
                return this.outputField;
            }
            set
            {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime verificationTimestamp
        {
            get
            {
                return this.verificationTimestampField;
            }
            set
            {
                this.verificationTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("verificationResult", IsNullable=false)]
        public verificationResult[] verificationResultList
        {
            get
            {
                return this.verificationResultListField;
            }
            set
            {
                this.verificationResultListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public enum verificationState
    {
        
        /// <remarks/>
        PASS,
        
        /// <remarks/>
        FAIL,
        
        /// <remarks/>
        NOT_EXECUTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class input
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class output
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public partial class abfrage_ergebnis
    {
        
        private System.DateTime ts_registrierungField;
        
        private abfrage_ergebnisStatus statusField;
        
        private System.DateTime ts_statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime ts_registrierung
        {
            get
            {
                return this.ts_registrierungField;
            }
            set
            {
                this.ts_registrierungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public abfrage_ergebnisStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime ts_status
        {
            get
            {
                return this.ts_statusField;
            }
            set
            {
                this.ts_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/rkdb")]
    public enum abfrage_ergebnisStatus
    {
        
        /// <remarks/>
        AKTIVIERT,
        
        /// <remarks/>
        REGISTRIERT,
        
        /// <remarks/>
        IN_BETRIEB,
        
        /// <remarks/>
        AUSFALL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class rkdbRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://finanzonline.bmf.gv.at/rkdb", Order=0)]
        public KassaExpert.FonConnector.Lib.RegKassaService.rkdbRequest rkdbRequest;
        
        public rkdbRequest1()
        {
        }
        
        public rkdbRequest1(KassaExpert.FonConnector.Lib.RegKassaService.rkdbRequest rkdbRequest)
        {
            this.rkdbRequest = rkdbRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class rkdbResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://finanzonline.bmf.gv.at/rkdb", Order=0)]
        public KassaExpert.FonConnector.Lib.RegKassaService.rkdbResponse rkdbResponse;
        
        public rkdbResponse1()
        {
        }
        
        public rkdbResponse1(KassaExpert.FonConnector.Lib.RegKassaService.rkdbResponse rkdbResponse)
        {
            this.rkdbResponse = rkdbResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface rkdbServicePortChannel : KassaExpert.FonConnector.Lib.RegKassaService.rkdbServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class rkdbServicePortClient : System.ServiceModel.ClientBase<KassaExpert.FonConnector.Lib.RegKassaService.rkdbServicePort>, KassaExpert.FonConnector.Lib.RegKassaService.rkdbServicePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public rkdbServicePortClient() : 
                base(rkdbServicePortClient.GetDefaultBinding(), rkdbServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.rkdb.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rkdbServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(rkdbServicePortClient.GetBindingForEndpoint(endpointConfiguration), rkdbServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rkdbServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(rkdbServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rkdbServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(rkdbServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rkdbServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<KassaExpert.FonConnector.Lib.RegKassaService.rkdbResponse1> rkdbAsync(KassaExpert.FonConnector.Lib.RegKassaService.rkdbRequest1 request)
        {
            return base.Channel.rkdbAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rkdb))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rkdb))
            {
                return new System.ServiceModel.EndpointAddress("https://finanzonline.bmf.gv.at/fonws/ws/rkdb");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return rkdbServicePortClient.GetBindingForEndpoint(EndpointConfiguration.rkdb);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return rkdbServicePortClient.GetEndpointAddress(EndpointConfiguration.rkdb);
        }
        
        public enum EndpointConfiguration
        {
            
            rkdb,
        }
    }
}
