//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KassaExpert.FonConnector.Lib.SessionService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://finanzonline.bmf.gv.at/fon/ws/session", ConfigurationName="KassaExpert.FonConnector.Lib.SessionService.sessionServicePort")]
    internal interface sessionServicePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="login", ReplyAction="*")]
        System.Threading.Tasks.Task<KassaExpert.FonConnector.Lib.SessionService.loginResponse> loginAsync(KassaExpert.FonConnector.Lib.SessionService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="logout", ReplyAction="*")]
        System.Threading.Tasks.Task<KassaExpert.FonConnector.Lib.SessionService.logoutResponse> logoutAsync(KassaExpert.FonConnector.Lib.SessionService.logoutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginRequest", Namespace="https://finanzonline.bmf.gv.at/fon/ws/session", Order=0)]
        public KassaExpert.FonConnector.Lib.SessionService.loginRequestBody Body;
        
        public loginRequest()
        {
        }
        
        public loginRequest(KassaExpert.FonConnector.Lib.SessionService.loginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://finanzonline.bmf.gv.at/fon/ws/session")]
    internal partial class loginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string benid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string herstellerid;
        
        public loginRequestBody()
        {
        }
        
        public loginRequestBody(string tid, string benid, string pin, string herstellerid)
        {
            this.tid = tid;
            this.benid = benid;
            this.pin = pin;
            this.herstellerid = herstellerid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="https://finanzonline.bmf.gv.at/fon/ws/session", Order=0)]
        public KassaExpert.FonConnector.Lib.SessionService.loginResponseBody Body;
        
        public loginResponse()
        {
        }
        
        public loginResponse(KassaExpert.FonConnector.Lib.SessionService.loginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://finanzonline.bmf.gv.at/fon/ws/session")]
    internal partial class loginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int rc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msg;
        
        public loginResponseBody()
        {
        }
        
        public loginResponseBody(string id, int rc, string msg)
        {
            this.id = id;
            this.rc = rc;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class logoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutRequest", Namespace="https://finanzonline.bmf.gv.at/fon/ws/session", Order=0)]
        public KassaExpert.FonConnector.Lib.SessionService.logoutRequestBody Body;
        
        public logoutRequest()
        {
        }
        
        public logoutRequest(KassaExpert.FonConnector.Lib.SessionService.logoutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://finanzonline.bmf.gv.at/fon/ws/session")]
    internal partial class logoutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string benid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        public logoutRequestBody()
        {
        }
        
        public logoutRequestBody(string tid, string benid, string id)
        {
            this.tid = tid;
            this.benid = benid;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class logoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="https://finanzonline.bmf.gv.at/fon/ws/session", Order=0)]
        public KassaExpert.FonConnector.Lib.SessionService.logoutResponseBody Body;
        
        public logoutResponse()
        {
        }
        
        public logoutResponse(KassaExpert.FonConnector.Lib.SessionService.logoutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://finanzonline.bmf.gv.at/fon/ws/session")]
    internal partial class logoutResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public logoutResponseBody()
        {
        }
        
        public logoutResponseBody(int rc, string msg)
        {
            this.rc = rc;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface sessionServicePortChannel : KassaExpert.FonConnector.Lib.SessionService.sessionServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class sessionServicePortClient : System.ServiceModel.ClientBase<KassaExpert.FonConnector.Lib.SessionService.sessionServicePort>, KassaExpert.FonConnector.Lib.SessionService.sessionServicePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public sessionServicePortClient() : 
                base(sessionServicePortClient.GetDefaultBinding(), sessionServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.session.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sessionServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(sessionServicePortClient.GetBindingForEndpoint(endpointConfiguration), sessionServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sessionServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(sessionServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sessionServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(sessionServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sessionServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<KassaExpert.FonConnector.Lib.SessionService.loginResponse> loginAsync(KassaExpert.FonConnector.Lib.SessionService.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<KassaExpert.FonConnector.Lib.SessionService.logoutResponse> logoutAsync(KassaExpert.FonConnector.Lib.SessionService.logoutRequest request)
        {
            return base.Channel.logoutAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.session))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.session))
            {
                return new System.ServiceModel.EndpointAddress("https://finanzonline.bmf.gv.at/fonws/ws/session");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return sessionServicePortClient.GetBindingForEndpoint(EndpointConfiguration.session);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return sessionServicePortClient.GetEndpointAddress(EndpointConfiguration.session);
        }
        
        public enum EndpointConfiguration
        {
            
            session,
        }
    }
}
